### ISSUE TITLE
KeyError in update_time() if duration value not sent

### ISSUE THREAD

**Issue by aaroncohen73** [osuosl/pymesync#145]
The documentation for Pymesync says that you only need to have the fields you wish to update in the dictionary that you send to update_time(), but Pymesync will always attempt to access time['duration'] without checking whether the key exists first. As a result, an error will be generated if the dictionary that is passed to update_time() doesn't contain a duration value.

Example:
```
>>> ts.update_time(uuid='71bf593d-ceeb-4000-87b7-754fca76d10a', time={'date_worked': '2016-05-19'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cohenaa/.venvs/climesync/local/lib/python2.7/site-packages/pymesync/pymesync.py", line 167, in update_time
    if time['duration'] < 0:
KeyError: 'duration'
```

**Comment by aaroncohen73** [comment]
Closed via #146
