### ISSUE TITLE
create/update user unable to handle Unicode password objects

### ISSUE THREAD

**Issue by aaroncohen73** [osuosl/pymesync#149]
The `bcrypt.hashpw()` function (Found inside `create_user()` and `update_user()`) is unable to hash Unicode objects. If the "password" field is passed in as a Unicode object, bcrypt complains by throwing a TypeError. Code should be added to these functions to detect Unicode objects and encode them with UTF-8.

Example:
```
>>> ts.create_user(user={u"username": u"unicodetest", u"password": u"unicodetest"})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pymesync/pymesync.py", line 268, in create_user
    rounds=10))
  File "/home/cohenaa/.venvs/pymesync/local/lib/python2.7/site-packages/bcrypt/__init__.py", line 57, in hashpw
    raise TypeError("Unicode-objects must be encoded before hashing")
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by aaroncohen73** [comment]
Closed via #150
